### ISSUE TITLE
setCurrent = 1 if pageSize is changed

### ISSUE THREAD

**Issue by xigualzn** [alibaba/hooks#1006]
https://github.com/alibaba/hooks/blob/404da7526a161b9f1aff645b44db5c387b5ba43f/packages/use-request/src/usePaginated.ts#L90

**Comment by nicoopy** [comment]
Hi xigualzn, I met the same problem these days. current page could not be manually change to 1 while pageSize has changed. Could i ask how did you solve this problem? Thanks a lot.

**Comment by brickspert** [comment]
You shuold trigger `onChange(1, pageSize)` instead of `changePageSize(pageSize)`. Maybe resolve it~

**Comment by nicoopy** [comment]
Appreciate～@砖家，I did solve this problem in this way(result.pagination.onChange(current, pageSize)).



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 10, 2021 15:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/hooks] setCurrent = 1 if pageSize is changed (#1006)




 
You shuold trigger onChange(1, pageSize) instead of changePageSize(pageSize). Maybe resolve it~
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cwtuan** [comment]
```
pagination.changeCurrent(1);
pagination.changePageSize(1000);
```
`changePageSize` will overwrite the `pageSize` value.

Workaround:
```
run({ current: 1, pageSize: 1000 }); 
```
