### ISSUE TITLE
[Bug Report] Avoid reading and writing `ref.current` during the rendering phase

### ISSUE THREAD

**Issue by SukkaW** [alibaba/hooks#1602]
Although the current React documentation doesn't mention it, according to [the React beta documentation](https://beta.reactjs.org/apis/useref):

> Do not write or read `ref.current` during rendering.
> React expects that the body of your component behaves like a pure function:
> - If the inputs (props, state, and context) are the same, it should return exactly the same JSX.
> - Calling it in a different order or with different arguments should not affect the results of other calls.
>
> Reading or writing a ref during rendering breaks these expectations.
>
> When you break these rules, your component might still work, but most of the newer features we’re adding to React will rely on these expectations.

**Comment by hchlq** [comment]
I think you're right. But in some scenes, ahooks  needs to use the features of React.useRef to achieve them.

I think the most important reason for using useRef instead of useState is:
the reference value of useRef remains unchanged in the update state of the component, which is very effective in getting the latest value in the closure of some functions, which cannot be done in useState or useReducer.

For the above two side effects:
ahooks most hooks use useRef to keep the intermediate state instead of JSX, but it may also have an indirect impact.

In general, although most of the hooks in ahooks do not use useRef very illegally, some hooks that change ref.current during rendering can be used as vigilance for developers, because we are not sure how developers use it.

**Comment by brickspert** [comment]
We'll take this seriously in our React 18 revamp, thank you for your feedback!

**Comment by brickspert** [comment]
https://zhuanlan.zhihu.com/p/514751791
