### ISSUE TITLE
useSelection Improvements

### ISSUE THREAD

**Issue by amcdnl** [alibaba/hooks#325]
The ability to do CTRL+Click or SHIFT+Click would be great additions.

Here is a similar feature I worked on that describes some of what this could look like: https://github.com/angular/components/issues/11309

**Comment by ttys026** [comment]
Hi @amcdnl, Thanks for your suggestion. 
We don't have a plan to support the keyboard combination yet. Since useSelection is focused on offering users a way to append/remove selections, but has nothing to do with how they add it.
The ability to do SHIFT+Click can be achieved by using useSelection along with [useKeyPress](https://hooks.umijs.org/hooks/dom/use-key-press)
